In [54]:
import numpy as np
import pickle

In [26]:
all_data = np.load('all_data.npy', allow_pickle=True)

In [28]:
np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=np.inf)

In [29]:
all_data = all_data.reshape((-1, 16))

In [32]:
print(len(all_data))

2245786


In [55]:
num_to_array = {}
array_to_num = {}

In [56]:
for num, array in enumerate(all_data):
    array_to_num[f'a{str(array)}'] = num
    num_to_array[num] = array

In [57]:
with open('num_to_array.pickle', 'wb') as file:
    pickle.dump(num_to_array, file)

In [58]:
with open('array_to_num.pickle', 'wb') as file:
    pickle.dump(array_to_num, file)

In [ ]:
'''[note_on_note, note_on_velocity,
        control_change_control, control_change_value, program_change_program,
        end_marking, set_tempo_tempo,
        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,
        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'''

In [30]:
unique_instrs = np.unique(all_data[:, -3])
print(unique_instrs)
print(len(unique_instrs))

[-1.  0.  2.  6.  7. 16. 18. 19. 20. 24. 25. 34. 40. 41. 42. 43. 45. 47. 48. 49. 51. 52. 53. 56. 57. 58. 59. 60. 63. 64. 65. 67. 68. 69. 70. 71. 73. 74. 75. 78. 79.]
41


In [31]:
all_notes = np.unique(all_data[:,0:2], axis = 0)
print(all_notes)
print(len(all_notes))

[[ -1.  -1.]
 [ 12.   0.]
 [ 12.  92.]
 [ 12. 100.]
 [ 14.   0.]
 [ 14.  92.]
 [ 14. 100.]
 [ 16.   0.]
 [ 16.  80.]
 [ 16.  84.]
 [ 16.  85.]
 [ 16.  86.]
 [ 16.  88.]
 [ 16. 100.]
 [ 17.   0.]
 [ 17.  88.]
 [ 17.  93.]
 [ 17. 100.]
 [ 18.   0.]
 [ 18.  80.]
 [ 18.  93.]
 [ 18.  94.]
 [ 18.  96.]
 [ 19.   0.]
 [ 19.  82.]
 [ 19.  85.]
 [ 19.  86.]
 [ 19.  88.]
 [ 19.  89.]
 [ 19.  90.]
 [ 19.  91.]
 [ 19.  93.]
 [ 19.  94.]
 [ 19.  97.]
 [ 19. 100.]
 [ 19. 102.]
 [ 20.   0.]
 [ 20.  80.]
 [ 21.   0.]
 [ 21.  76.]
 [ 21.  80.]
 [ 21.  82.]
 [ 21.  83.]
 [ 21.  84.]
 [ 21.  86.]
 [ 21.  88.]
 [ 21.  89.]
 [ 21.  90.]
 [ 21.  94.]
 [ 21.  96.]
 [ 21.  98.]
 [ 21. 100.]
 [ 22.   0.]
 [ 22.  96.]
 [ 22.  97.]
 [ 22.  98.]
 [ 22. 100.]
 [ 23.   0.]
 [ 23.  80.]
 [ 23.  83.]
 [ 23.  88.]
 [ 23.  89.]
 [ 23.  90.]
 [ 23.  92.]
 [ 23.  94.]
 [ 23. 100.]
 [ 24.   0.]
 [ 24.  36.]
 [ 24.  49.]
 [ 24.  64.]
 [ 24.  77.]
 [ 24.  79.]
 [ 24.  80.]
 [ 24.  83.]
 [ 24.  84.]
 [ 24.  85.]
 [ 24.  86.]

In [33]:
print(np.unique(all_data[:,0], axis = 0))
print(np.unique(all_data[:,1], axis = 0))

[ -1.  12.  14.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 112. 113. 114. 115.]
[ -1.   0.   1.  10.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100. 101. 102. 103. 104. 105. 10

In [46]:
unique_time = np.unique(all_data[:, -4])

In [52]:
print(len(unique_time))

293479


In [51]:
print(np.max(unique_time))
#seriously?? Why is it so large
print(np.average(unique_time))
print(np.std(unique_time))

2998560.0
309953.23545125884
475302.85297067114


In [53]:
print(np.unique(all_data[:,2], axis = 0))
#basically not much
print(np.unique(all_data[:,3], axis = 0))
#basically everything

[ -1.   0.   1.   7.   8.  10.  11.  32.  52.  91.  93. 121.]
[ -1.   0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126. 127.]
