In [1]:
import pickle
import numpy as np

In [2]:
all_data = []
with (open("all_data.pickle", "rb")) as openfile:
    try:
        all_data = (pickle.load(openfile))
    except EOFError:
        pass

In [3]:
new_data = []

In [4]:
array_to_num_dic = {}
with (open('array_to_num.pickle', 'rb')) as openfile:
    try:
        array_to_num_dic = (pickle.load(openfile))
    except EOFError:
        pass

In [16]:
for i in range(len(all_data)):
    cur_array = np.array([])
    this_data = all_data[i]
    for k in range(len(this_data)):
        cur_array = np.append(cur_array, array_to_num_dic[f"a{''.join(str(this_data[k]).splitlines())}"])
    new_data.append(cur_array)

In [17]:
with (open('all_data_2.pickle', 'wb')) as openfile:
    pickle.dump(new_data, openfile)

In [23]:
print(len(new_data))
print(len(all_data))

374
362


In [24]:
print(len(all_data[0]))
print(len(new_data[0]))

25484
25484


In [26]:
new_data[0]

array([  9943.,   9949.,   9950., ..., 133041., 319207.,   9656.])

In [28]:
new_data[len(new_data)-1]

array([  9991.,    304.,   6701., ..., 161439., 164389.,   9577.])

In [29]:
all_data[len(all_data)-1]

array([[ -1,  -1,  -1, ...,  24,   1,  24],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1],
       ...,
       [ 63,   0,  -1, ...,  24,   1,  24],
       [ 63, 100,  -1, ...,  24,   1,  24],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1]], dtype=int64)

In [ ]:
# why added rows????