In [21]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import pickle

In [22]:
with open("final_data.pickle", "rb") as f:
    data = pickle.load(f)

In [23]:
inputs = []
target = []
for i in range(len(data)):
    inputs.append(data[i][0:-1])
    target.append(data[i][1:])

In [24]:
inputs[0]

array([[0.000e+00, 0.000e+00, 0.000e+00],
       [3.700e+01, 0.000e+00, 5.000e+00],
       [3.500e+01, 0.000e+00, 7.000e+00],
       ...,
       [2.008e+03, 3.000e+00, 5.000e+00],
       [3.163e+03, 3.000e+00, 5.000e+00],
       [4.928e+03, 0.000e+00, 5.000e+00]])

In [25]:
target[0]

array([[3.700e+01, 0.000e+00, 5.000e+00],
       [3.500e+01, 0.000e+00, 7.000e+00],
       [3.500e+01, 0.000e+00, 4.400e+01],
       ...,
       [3.163e+03, 3.000e+00, 5.000e+00],
       [4.928e+03, 0.000e+00, 5.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00]])

In [26]:
# traintest split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=42)
# dev set split
X_train, X_dev, y_train, y_dev = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [27]:
print(len(X_train))
print(len(X_dev))
print(len(X_test))

234
59
74


In [28]:
def get_len(data):
    length = 0
    for i in range(len(data)):
        length += len(data[i])
    return length

In [29]:
print(get_len(X_train))
print(get_len(X_dev))
print(get_len(X_test))

1552093
370242
513827


In [35]:
vals = []
for i in range(len(inputs)):
    vals.append(len(inputs[i]))
print(np.sort(vals))

[    17    223    225    227    347    379    396    438    445    588
    606    630    649    677    751    812    813    836    839    858
    876    878    883    959   1050   1058   1058   1061   1062   1064
   1080   1097   1109   1122   1129   1139   1145   1161   1174   1183
   1212   1223   1253   1266   1269   1310   1318   1322   1326   1341
   1366   1391   1397   1416   1429   1429   1443   1490   1492   1505
   1505   1523   1528   1555   1571   1578   1579   1607   1621   1623
   1637   1639   1641   1664   1669   1719   1725   1740   1745   1769
   1769   1788   1789   1791   1829   1854   1866   1882   1890   1891
   1913   1936   1940   1941   1954   1965   1965   1989   1989   1997
   2019   2023   2023   2051   2072   2103   2107   2138   2139   2139
   2145   2172   2191   2193   2222   2225   2235   2242   2265   2296
   2296   2376   2380   2412   2431   2447   2470   2471   2476   2506
   2516   2562   2578   2587   2598   2635   2641   2644   2675   2708
   271

In [19]:
data_values = np.array([])
data_times = np.array([])
data_instruments = np.array([])

In [20]:
for i in range(len(data)):
    for j in range(len(data[i])):
        data_values = np.append(data_values, data[i][j][0])
        data_times = np.append(data_times, data[i][j][1])
        data_instruments = np.append(data_instruments, data[i][j][2])

KeyboardInterrupt: 

In [12]:
data_values = np.array(data_values)
data_times = np.array(data_times)
data_instruments = np.array(data_instruments)

In [13]:
data_values[0:100]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])