In [2]:
import tensorflow as tf
from keras import layers, models
from keras.layers import Layer, Embedding, Dense, Dropout, LayerNormalization
import numpy as np
from keras.models import Model
import pickle


In [3]:
def create_padding_mask(seq, n=4):
    mask = tf.cast(seq == -1, tf.float32)
    return tf.reshape(mask, (tf.shape(mask)[0], *(1,) * (n - 2), tf.shape(mask)[-1]))


def create_look_ahead_mask(seq_len):
    mask = 1 - tf.linalg.band_part(tf.ones((seq_len, seq_len)), -1, 0)
    return tf.cast(mask, tf.float32)


def create_mask(inp, n=4):
    padding_mask = create_padding_mask(inp, n)
    seq_len = tf.shape(inp)[1]  # Get the sequence length dynamically
    look_ahead_mask = create_look_ahead_mask(seq_len)
    return tf.maximum(padding_mask, look_ahead_mask)

In [14]:
def create_tokenized_data(data):
    input_data = []
    output_data = []
    for i in range(0, len(data)):
        input_data.append(np.insert(data[:i], 0, -1))
        output_data.append(data[i])
    return input_data,output_data

In [15]:
create_tokenized_data(np.array([1,2,3,4]))

([array([-1]), array([-1,  1]), array([-1,  1,  2]), array([-1,  1,  2,  3])],
 [1, 2, 3, 4])

In [5]:
with (open("all_data_2.pickle", "rb")) as openfile:
    data = pickle.load(openfile)

In [6]:
data

[array([  9943.,   9949.,   9950., ..., 133041., 319207.,   9656.]),
 array([  9949.,   9950.,   9951., ..., 242692., 202016.,   9698.]),
 array([ 10054.,  10271.,  10298., ..., 285245., 359390.,   9597.]),
 array([ 10199.,  10289.,  10290., ..., 285203., 319249.,   9652.]),
 array([10289., 10298., 10299., ..., 19729., 36735.,  9775.]),
 array([  9944.,   9945.,   9949., ..., 303344., 369495.,   9747.]),
 array([  9949.,   9950.,   9951., ...,  98203., 202487.,   9836.]),
 array([1.02080e+04, 1.03000e+04, 1.16000e+02, ..., 1.07840e+04,
        3.19254e+05, 9.58100e+03]),
 array([ 10271.,  10303.,  10304., ..., 123406., 242911.,   9736.]),
 array([10035., 10248., 10265., ..., 35263., 36416.,  9584.]),
 array([ 9949.,  9950.,  9951., ..., 19487., 35278.,  9634.]),
 array([ 10035.,  10054.,  10194., ...,  42929., 222668.,   9595.]),
 array([  9949.,   9950.,   9951., ..., 242757., 280951.,   9719.]),
 array([  9991.,   9992.,   9993., ..., 142181., 218040.,   9871.]),
 array([  9944.,   9

In [7]:
with (open("num_to_array.pickle", "rb")) as openfile:
    num_to_array = pickle.load(openfile)