In [2]:
import os
import numpy as np
from MIDI_data_extractor import MIDI_data_extractor
import pickle

In [3]:
def extract_all_to_nums(input_path):
    # go to all MIDI files in folder and extract data from path, go to all subfolders and do the same
    # return numpy array of all data
    # Note: MIDI_data_extractor takes in input_path of MIDI file
    os.chdir(r"C:\Users\ilove\CODING\PYStuff\MusicNet\Midi2Numpy\MIDI-Generator-with-Transformers")
    os.chdir(input_path)
    cur_data = []
    try:
        for root, dirs, files in os.walk(input_path):
            #print(dirs,files)
            for file in files:
                if file.endswith(".mid"):
                    data = MIDI_data_extractor(os.path.join(root, file), 0, True)
                    #check if any of data's indexes -4 is negative or greater than 10000
                    #if so, print the file name and index
                    if np.any(data[:, -4] < -1):
                        print("Negative????")
                        print(file)
                        print(root)
                    cur_data.append(data)
            for dirs in dirs:
                extract_all_to_nums(os.path.join(root, dirs))
    except KeyboardInterrupt:
        return cur_data
    return cur_data
all_data = (extract_all_to_nums(r"C:\Users\ilove\CODING\PYStuff\MusicNet\Midi2Numpy\MIDI-Generator-with-Transformers\Bach MIDIs"))

[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]
[-1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1]


In [4]:
all_data[0]

array([[   -1,    -1,    -1,    -1,    -1,     0,    -1,    -1,    -1,    -1,    -1,    -1,     0,    -1,    -1,    -1],
       [   -1,    -1,    -1,    -1,    16,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    16,     1,    16],
       [   -1,    -1,    -1,    -1,    19,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    19,     1,    19],
       [   -1,    -1,    -1,    -1,    19,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    19,     2,    19],
       [   -1,    -1,    -1,    -1,    19,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    19,     3,    19],
       [   -1,    -1,    -1,    -1,    56,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    56,     1,    56],
       [   -1,    -1,    -1,    -1,    56,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    56,     2,    56],
       [   -1,    -1,    -1,    -1,    56,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     0,    56,     3,    56],
       [   -1,    -1,    -1,    

In [5]:
#save all_data as pickle
with open('all_data.pickle', 'wb') as f:
    pickle.dump(all_data, f)

In [4]:
full_data = np.array([])
for i in range(len(all_data)):
    full_data = np.append(full_data, all_data[i])
full_data = full_data.reshape((-1,16))

In [5]:
os.chdir(r"C:\Users\ilove\CODING\PYStuff\MusicNet\Midi2Numpy\MIDI-Generator-with-Transformers")
with open('all_data.npy', 'wb') as f:
    np.save(f,full_data)

In [6]:
unique_data = np.unique(full_data, axis = 0)

In [7]:
os.chdir(r"C:\Users\ilove\CODING\PYStuff\MusicNet\Midi2Numpy\MIDI-Generator-with-Transformers")
with open('all_unique_data.npy', 'wb') as f:
    np.save(f,unique_data)

In [8]:
#seriously wtf??

In [9]:
# os.chdir(r"C:\Users\ilove\CODING\PYStuff\MusicNet\Midi2Numpy\MIDI-Generator-with-Transformers")
# with open('all_data.pickle', 'wb') as f:
#    pickle.dump(all_data, f)
'''[note_on_note, note_on_velocity,
        control_change_control, control_change_value, program_change_program,
        end_marking, set_tempo_tempo,
        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,
        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'''

'[note_on_note, note_on_velocity,\n        control_change_control, control_change_value, program_change_program,\n        end_marking, set_tempo_tempo,\n        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,\n        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'