In [1]:
import pickle
import numpy as np

In [13]:
all_data = []
with (open("fixed_all_data.pickle", "rb")) as openfile:
    try:
        all_data = (pickle.load(openfile))
    except EOFError:
        pass

In [14]:
all_data[0]

array([[-1, -1, -1, ...,  0, -1, -1],
       [-1, -1, -1, ...,  0,  1, 16],
       [-1, -1, -1, ...,  0,  1, 19],
       ...,
       [60,  0, -1, ...,  3,  1, 16],
       [77,  0, -1, ...,  0,  1, 16],
       [-1, -1, -1, ...,  0, -1, -1]], dtype=int64)

In [15]:
new_data = []

In [16]:
with open('values_to_num.pickle', 'rb') as handle:
    values_to_num = pickle.load(handle)

In [17]:
with open('time_to_num.pickle', 'rb') as handle:
    time_to_num = pickle.load(handle)

In [18]:
with open('instruments_to_num.pickle', 'rb') as handle:
    instruments_to_num = pickle.load(handle)

In [20]:
for i in range(len(all_data)):
    cur_data = np.array([])
    for j in range(len(all_data[i])):
        this_data = all_data[i][j]
        new_cur_data = np.array([])
        values = this_data[0:12]
        time = this_data[12]
        instruments = this_data[13:]
        new_cur_data = np.append(new_cur_data, values_to_num[str(values)])
        new_cur_data = np.append(new_cur_data, time_to_num[str(time)])
        new_cur_data = np.append(new_cur_data, instruments_to_num[str(instruments)])
        cur_data = np.append(cur_data, new_cur_data)
    new_data.append(cur_data)

In [21]:
with open('final_data.pickle', 'wb') as handle:
    pickle.dump(new_data, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [22]:
new_data[0]

array([0., 0., 0., ..., 1., 0., 0.])

In [29]:
shaped_data = []

In [30]:
for i in range(len(new_data)):
    shaped_data.append(new_data[i].reshape(-1, 3))

In [31]:
len(all_data[0])

25485

In [32]:
shaped_data[0]

array([[0.000e+00, 0.000e+00, 0.000e+00],
       [3.700e+01, 0.000e+00, 5.000e+00],
       [3.500e+01, 0.000e+00, 7.000e+00],
       ...,
       [3.163e+03, 3.000e+00, 5.000e+00],
       [4.928e+03, 0.000e+00, 5.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00]])

In [33]:
len(shaped_data[0])

25485

In [34]:
with open('final_data.pickle', 'wb') as handle:
    pickle.dump(shaped_data, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [35]:
with open('final_data.pickle', 'rb') as handle:
    shaped_data = pickle.load(handle)

In [36]:
shaped_data[0]

array([[0.000e+00, 0.000e+00, 0.000e+00],
       [3.700e+01, 0.000e+00, 5.000e+00],
       [3.500e+01, 0.000e+00, 7.000e+00],
       ...,
       [3.163e+03, 3.000e+00, 5.000e+00],
       [4.928e+03, 0.000e+00, 5.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00]])