In [1]:
import pickle
import numpy as np

In [2]:
with (open("all_data.pickle", "rb")) as openfile:
    try:
        all_data = (pickle.load(openfile))
    except EOFError:
        pass

In [3]:
len(all_data)

362

In [5]:
all_data[0]
# why did it change from original all_data??

array([[-1, -1, -1, ..., 16,  1, 16],
       [-1, -1, -1, ..., 19,  1, 19],
       [-1, -1, -1, ..., 19,  2, 19],
       ...,
       [60,  0, -1, ..., 16,  1, 16],
       [77,  0, -1, ..., 16,  1, 16],
       [-1, -1, -1, ..., -1, -1, -1]], dtype=int64)

In [6]:
fixed_all_data=all_data

In [7]:
for i in range(len(all_data)):
    # go to last index, go to 5th index then turn it into 1
    fixed_all_data[i][-1][5] = 1
    # append row of -1's to start of array then turn 5th index into 0
    neg_array = np.full((1, 16), -1)
    neg_array[0][5] = 0
    fixed_all_data[i] = np.vstack([neg_array, fixed_all_data[i]])

In [8]:
fixed_all_data[0]

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., 16,  1, 16],
       [-1, -1, -1, ..., 19,  1, 19],
       ...,
       [60,  0, -1, ..., 16,  1, 16],
       [77,  0, -1, ..., 16,  1, 16],
       [-1, -1, -1, ..., -1, -1, -1]], dtype=int64)

In [9]:
with open('fixed_all_data.pickle', 'wb') as f:
    pickle.dump(fixed_all_data, f)

In [10]:
with open('fixed_all_data.pickle', 'rb') as f:
    fixed_all_data = pickle.load(f)

In [14]:
fixed_all_data[0]

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., 16,  1, 16],
       ...,
       [60,  0, -1, ..., 16,  1, 16],
       [77,  0, -1, ..., 16,  1, 16],
       [-1, -1, -1, ..., -1, -1, -1]], dtype=int64)

In [ ]:
#fixed

In [11]:
total_length = 0
for i in all_data:
    total_length += len(i)

In [12]:
total_length

2384400

In [13]:
#get largest value within all_data
largest_values = []
for i in all_data:
    largest_values.append(np.max(i))
print(np.max(largest_values))

598984


In [14]:
largest_lengths = np.array([])
for i in all_data:
    largest_lengths = np.append(largest_lengths, len(i))
largest_lengths = np.sort(largest_lengths)
print(largest_lengths)

[1.70000e+01 2.23000e+02 2.25000e+02 2.27000e+02 3.47000e+02 3.79000e+02
 3.96000e+02 4.38000e+02 4.45000e+02 5.88000e+02 6.06000e+02 6.30000e+02
 6.49000e+02 6.77000e+02 7.51000e+02 8.12000e+02 8.13000e+02 8.36000e+02
 8.39000e+02 8.58000e+02 8.76000e+02 8.78000e+02 8.83000e+02 9.59000e+02
 1.05000e+03 1.05800e+03 1.05800e+03 1.06100e+03 1.06200e+03 1.06400e+03
 1.08000e+03 1.09700e+03 1.10900e+03 1.12200e+03 1.12900e+03 1.13900e+03
 1.14500e+03 1.16100e+03 1.17400e+03 1.18300e+03 1.21200e+03 1.22300e+03
 1.25300e+03 1.26600e+03 1.26900e+03 1.31000e+03 1.31800e+03 1.32200e+03
 1.32600e+03 1.34100e+03 1.36600e+03 1.39100e+03 1.39700e+03 1.41600e+03
 1.42900e+03 1.42900e+03 1.44300e+03 1.49000e+03 1.49200e+03 1.50500e+03
 1.50500e+03 1.52300e+03 1.52800e+03 1.55500e+03 1.57100e+03 1.57800e+03
 1.57900e+03 1.60700e+03 1.62100e+03 1.62300e+03 1.63700e+03 1.63900e+03
 1.64100e+03 1.66400e+03 1.66900e+03 1.71900e+03 1.72500e+03 1.74000e+03
 1.74500e+03 1.76900e+03 1.76900e+03 1.78800e+03 1.

In [15]:
largest_lengths

array([1.70000e+01, 2.23000e+02, 2.25000e+02, 2.27000e+02, 3.47000e+02,
       3.79000e+02, 3.96000e+02, 4.38000e+02, 4.45000e+02, 5.88000e+02,
       6.06000e+02, 6.30000e+02, 6.49000e+02, 6.77000e+02, 7.51000e+02,
       8.12000e+02, 8.13000e+02, 8.36000e+02, 8.39000e+02, 8.58000e+02,
       8.76000e+02, 8.78000e+02, 8.83000e+02, 9.59000e+02, 1.05000e+03,
       1.05800e+03, 1.05800e+03, 1.06100e+03, 1.06200e+03, 1.06400e+03,
       1.08000e+03, 1.09700e+03, 1.10900e+03, 1.12200e+03, 1.12900e+03,
       1.13900e+03, 1.14500e+03, 1.16100e+03, 1.17400e+03, 1.18300e+03,
       1.21200e+03, 1.22300e+03, 1.25300e+03, 1.26600e+03, 1.26900e+03,
       1.31000e+03, 1.31800e+03, 1.32200e+03, 1.32600e+03, 1.34100e+03,
       1.36600e+03, 1.39100e+03, 1.39700e+03, 1.41600e+03, 1.42900e+03,
       1.42900e+03, 1.44300e+03, 1.49000e+03, 1.49200e+03, 1.50500e+03,
       1.50500e+03, 1.52300e+03, 1.52800e+03, 1.55500e+03, 1.57100e+03,
       1.57800e+03, 1.57900e+03, 1.60700e+03, 1.62100e+03, 1.623

In [16]:
all_numpy_data = np.load("all_data.npy")

In [17]:
np.count_nonzero(all_numpy_data[:,5] == 0)

362

In [18]:
all_numpy_data[0]

array([-1., -1., -1., -1., -1.,  0., -1., -1., -1., -1., -1., -1.,  0.,
       -1., -1., -1.])

In [19]:
un_full_data = np.load('all_unique_data.npy')

In [20]:
'''[note_on_note, note_on_velocity,
        control_change_control, control_change_value, program_change_program,
        end_marking, set_tempo_tempo,
        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,
        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'''

'[note_on_note, note_on_velocity,\n        control_change_control, control_change_value, program_change_program,\n        end_marking, set_tempo_tempo,\n        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,\n        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'

In [21]:
len(un_full_data)

371710

In [22]:
data_wo_time = un_full_data[:,[0,1,2,3,4,5,6,7,8,9,10,11,13,14,15]]

In [23]:
data_wo_time = np.unique(data_wo_time, axis = 0)

In [24]:
len(data_wo_time)

62782

In [25]:
data_instrs = un_full_data[:,[13,14,15]]

In [26]:
data_instrs = np.unique(data_instrs, axis = 0)

In [27]:
len(data_instrs)

229

In [28]:
data_instrs_wo_instr_type = un_full_data[:,[14,15]]

In [29]:
data_instrs_wo_instr_type = np.unique(data_instrs_wo_instr_type, axis = 0)

In [30]:
len(data_instrs_wo_instr_type)

143

In [31]:
data_wo_instruments_or_time = un_full_data[:,[0,1,2,3,4,5,6,7,8,9,10,11]]

In [32]:
data_wo_instruments_or_time = np.unique(data_wo_instruments_or_time, axis = 0)

In [33]:
len(data_wo_instruments_or_time)

6329

In [34]:
data_time_sig_num_den = un_full_data[:,[7,8]]

In [35]:
data_time_sig_num_den = np.unique(data_time_sig_num_den, axis = 0)

In [36]:
len(data_time_sig_num_den)

25

In [37]:
data_time_sig_num_den

array([[-1., -1.],
       [ 1.,  2.],
       [ 1.,  4.],
       [ 1.,  8.],
       [ 1., 16.],
       [ 2.,  2.],
       [ 2.,  4.],
       [ 2.,  8.],
       [ 3.,  2.],
       [ 3.,  4.],
       [ 3.,  8.],
       [ 4.,  2.],
       [ 4.,  4.],
       [ 5.,  8.],
       [ 6.,  4.],
       [ 6.,  8.],
       [ 8.,  4.],
       [ 8.,  8.],
       [ 9.,  4.],
       [ 9.,  8.],
       [ 9., 16.],
       [11.,  8.],
       [12.,  8.],
       [12., 16.],
       [15., 16.]])

In [38]:
# what the heck is 15/16 time??

In [39]:
times = un_full_data[:,[12]]

In [40]:
times = np.unique(times, axis = 0)

In [41]:
len(times)

3904

In [42]:
times

array([[0.00000e+00],
       [1.00000e+00],
       [2.00000e+00],
       ...,
       [5.98862e+05],
       [5.98970e+05],
       [5.98984e+05]])

In [43]:
# data with times and instruments
data_time_and_instrs = un_full_data[:,[12,13,14,15]]

In [44]:
data_time_and_instrs = np.unique(data_time_and_instrs, axis = 0)

In [45]:
len(data_time_and_instrs)

33825

In [46]:
data_time_and_instrs

array([[ 0.00000e+00, -1.00000e+00, -1.00000e+00, -1.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  1.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  2.00000e+00,  0.00000e+00],
       ...,
       [ 5.98970e+05,  4.80000e+01,  2.00000e+00,  4.80000e+01],
       [ 5.98970e+05,  4.80000e+01,  3.00000e+00,  4.80000e+01],
       [ 5.98984e+05,  5.60000e+01,  1.00000e+00,  5.60000e+01]])

In [47]:
data_time_and_instrs_wo_instr_type = un_full_data[:,[12,14,15]]

In [48]:
data_time_and_instrs_wo_instr_type = np.unique(data_time_and_instrs_wo_instr_type, axis = 0)

In [49]:
len(data_time_and_instrs_wo_instr_type)

31012

In [50]:
data_time_and_instrs_wo_instr_type

array([[ 0.00000e+00, -1.00000e+00, -1.00000e+00],
       [ 0.00000e+00,  1.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  1.00000e+00,  2.00000e+00],
       ...,
       [ 5.98970e+05,  2.00000e+00,  4.80000e+01],
       [ 5.98970e+05,  3.00000e+00,  4.80000e+01],
       [ 5.98984e+05,  1.00000e+00,  5.60000e+01]])