In [3]:
import pickle
import numpy as np

In [4]:
with (open("all_data.pickle", "rb")) as openfile:
    try:
        all_data = (pickle.load(openfile))
    except EOFError:
        pass

In [5]:
len(all_data)

419

In [6]:
with (open("music_len_to_pairing.pickle", 'rb')) as openfile:
    try:
        music_len_to_pairing = (pickle.load(openfile))
    except EOFError:
        pass

In [7]:
len(music_len_to_pairing)

409

In [8]:
all_data[0]

array([[  0,   0,  -1, ...,  -1,  -1,  -1],
       [  1,   0,  -1, ...,   0,   1,   0],
       [  1,  16,  -1, ...,  16,   1,  16],
       ...,
       [  6,  96,   0, ...,  73,   2,  73],
       [  6, 101,   0, ...,  73,   1,  73],
       [  0,   1,  -1, ...,  -1,  -1,  -1]], dtype=int64)

In [9]:
#drop index 13 of each array
for i in range(len(all_data)):
    all_data[i] = np.delete(all_data[i], 8, 1)

In [10]:
with open('simplified_all_data.pickle', 'wb') as f:
    pickle.dump(all_data, f)

In [11]:
with open('simplified_all_data.pickle', 'rb') as f:
    fixed_all_data = pickle.load(f)

In [12]:
fixed_all_data[0]

array([[  0,   0,  -1, ...,   0,  -1,  -1],
       [  1,   0,  -1, ...,   0,   1,   0],
       [  1,  16,  -1, ...,   0,   1,  16],
       ...,
       [  6,  96,   0, ...,   0,   2,  73],
       [  6, 101,   0, ...,   0,   1,  73],
       [  0,   1,  -1, ...,   0,  -1,  -1]], dtype=int64)

In [13]:
full_numpy_array = np.array([])
for i in fixed_all_data:
    full_numpy_array = np.append(full_numpy_array, i)

In [14]:
full_numpy_array = np.reshape(full_numpy_array, (-1, 10))

In [15]:
np.save('all_data.npy', full_numpy_array)

In [17]:
unique_numpy_array = np.unique(full_numpy_array, axis = 0)

In [18]:
np.save('all_unique_data.npy', unique_numpy_array)

In [19]:
total_length = 0
for i in all_data:
    total_length += len(i)

In [20]:
total_length

2678588

In [21]:
#get largest value within all_data
largest_values = []
for i in all_data:
    largest_values.append(np.max(i))
print(np.max(largest_values))

1053841


In [22]:
largest_lengths = np.array([])
for i in all_data:
    largest_lengths = np.append(largest_lengths, len(i))
largest_lengths = np.sort(largest_lengths)
print(largest_lengths)

[   242.    313.    315.    412.    460.    479.    490.    555.    616.
    649.    663.    672.    704.    785.    819.    832.    846.    851.
    858.    872.    878.    894.    900.    901.    977.    994.   1067.
   1070.   1072.   1078.   1079.   1079.   1097.   1114.   1130.   1141.
   1146.   1156.   1157.   1167.   1182.   1182.   1204.   1217.   1232.
   1234.   1239.   1254.   1256.   1274.   1274.   1276.   1288.   1296.
   1304.   1310.   1312.   1314.   1330.   1336.   1337.   1342.   1342.
   1347.   1363.   1382.   1393.   1406.   1408.   1412.   1412.   1426.
   1436.   1450.   1462.   1465.   1486.   1502.   1510.   1511.   1514.
   1517.   1528.   1544.   1550.   1552.   1588.   1592.   1597.   1600.
   1608.   1620.   1623.   1643.   1644.   1658.   1659.   1659.   1684.
   1688.   1696.   1725.   1736.   1738.   1746.   1758.   1789.   1790.
   1799.   1808.   1808.   1858.   1862.   1887.   1901.   1922.   1934.
   1940.   1940.   1941.   1943.   1950.   1962.   

In [23]:
largest_lengths

array([   242.,    313.,    315.,    412.,    460.,    479.,    490.,
          555.,    616.,    649.,    663.,    672.,    704.,    785.,
          819.,    832.,    846.,    851.,    858.,    872.,    878.,
          894.,    900.,    901.,    977.,    994.,   1067.,   1070.,
         1072.,   1078.,   1079.,   1079.,   1097.,   1114.,   1130.,
         1141.,   1146.,   1156.,   1157.,   1167.,   1182.,   1182.,
         1204.,   1217.,   1232.,   1234.,   1239.,   1254.,   1256.,
         1274.,   1274.,   1276.,   1288.,   1296.,   1304.,   1310.,
         1312.,   1314.,   1330.,   1336.,   1337.,   1342.,   1342.,
         1347.,   1363.,   1382.,   1393.,   1406.,   1408.,   1412.,
         1412.,   1426.,   1436.,   1450.,   1462.,   1465.,   1486.,
         1502.,   1510.,   1511.,   1514.,   1517.,   1528.,   1544.,
         1550.,   1552.,   1588.,   1592.,   1597.,   1600.,   1608.,
         1620.,   1623.,   1643.,   1644.,   1658.,   1659.,   1659.,
         1684.,   16

In [ ]:
all_numpy_data = np.load("all_data.npy")

In [ ]:
np.count_nonzero(all_numpy_data[:,5] == 0)

In [ ]:
all_numpy_data[0]

In [ ]:
un_full_data = np.load('all_unique_data.npy')

In [ ]:
'''[note_on_note, note_on_velocity,
        control_change_control, control_change_value, program_change_program,
        end_marking, set_tempo_tempo,
        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,
        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'''

In [ ]:
len(un_full_data)

In [ ]:
data_wo_time = un_full_data[:,[0,1,2,3,4,5,6,7,8,9,10,11,13,14,15]]

In [ ]:
data_wo_time = np.unique(data_wo_time, axis = 0)

In [ ]:
len(data_wo_time)

In [ ]:
data_instrs = un_full_data[:,[13,14,15]]

In [ ]:
data_instrs = np.unique(data_instrs, axis = 0)

In [ ]:
len(data_instrs)

In [ ]:
data_instrs_wo_instr_type = un_full_data[:,[14,15]]

In [ ]:
data_instrs_wo_instr_type = np.unique(data_instrs_wo_instr_type, axis = 0)

In [ ]:
len(data_instrs_wo_instr_type)

In [ ]:
data_wo_instruments_or_time = un_full_data[:,[0,1,2,3,4,5,6,7,8,9,10,11]]

In [ ]:
data_wo_instruments_or_time = np.unique(data_wo_instruments_or_time, axis = 0)

In [ ]:
len(data_wo_instruments_or_time)

In [ ]:
data_time_sig_num_den = un_full_data[:,[7,8]]

In [ ]:
data_time_sig_num_den = np.unique(data_time_sig_num_den, axis = 0)

In [ ]:
len(data_time_sig_num_den)

In [ ]:
data_time_sig_num_den

In [ ]:
# what the heck is 15/16 time??

In [ ]:
times = un_full_data[:,[12]]

In [ ]:
times = np.unique(times, axis = 0)

In [ ]:
len(times)

In [ ]:
times

In [ ]:
# data with times and instruments
data_time_and_instrs = un_full_data[:,[12,13,14,15]]

In [ ]:
data_time_and_instrs = np.unique(data_time_and_instrs, axis = 0)

In [ ]:
len(data_time_and_instrs)

In [ ]:
data_time_and_instrs

In [ ]:
data_time_and_instrs_wo_instr_type = un_full_data[:,[12,14,15]]

In [ ]:
data_time_and_instrs_wo_instr_type = np.unique(data_time_and_instrs_wo_instr_type, axis = 0)

In [ ]:
len(data_time_and_instrs_wo_instr_type)

In [ ]:
data_time_and_instrs_wo_instr_type