In [9]:
import numpy as np
import pickle
np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=np.inf)

In [10]:
all_data_o = np.load('all_unique_data.npy', allow_pickle=True)

In [11]:
all_data_o[0]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  9.,  0.,  1.,  6.])

In [12]:
all_data = all_data_o.reshape((-1, 15))
#change dtype of all_data to int64

all_data = all_data.astype(np.int64)

In [13]:
# sort all_data so that the value are in order in this order: index 5, index 4

all_data_2 = all_data[np.lexsort((-all_data[:,4], -all_data[:,5]))]

In [14]:
all_data_2 = all_data_2.reshape((-1, 15))

In [15]:
all_data_2[0:10000]

array([[    -1,     -1,     -1,     -1,     -1,      1,     -1,     -1,     -1,     -1,     -1,     -1,      0,     -1,     -1],
       [    -1,     -1,     -1,     -1,     -1,      0,     -1,     -1,     -1,     -1,     -1,     -1,      0,     -1,     -1],
       [    -1,     -1,     -1,     -1,     79,     -1,     -1,     -1,     -1,     -1,     -1,     -1,      0,      1,     79],
       [    -1,     -1,     -1,     -1,     79,     -1,     -1,     -1,     -1,     -1,     -1,     -1,      0,      2,     24],
       [    -1,     -1,     -1,     -1,     79,     -1,     -1,     -1,     -1,     -1,     -1,     -1,      0,      2,     79],
       [    -1,     -1,     -1,     -1,     79,     -1,     -1,     -1,     -1,     -1,     -1,     -1,      0,      3,     19],
       [    -1,     -1,     -1,     -1,     79,     -1,     -1,     -1,     -1,     -1,     -1,     -1,      0,      3,     79],
       [    -1,     -1,     -1,     -1,     79,     -1,     -1,     -1,     -1,     -1,     -1,  

In [16]:
# pickle values up to index 11 (values), pickle index 12 (time), pickle values from index 14 to end (instruments)

In [17]:
num_to_values = {}
values_to_num = {}
time_to_num = {}
num_to_times = {}
num_to_instruments = {}
instruments_to_num = {}

In [18]:
values_count = 0
time_count = 0
instruments_count = 0

In [19]:
values_array = np.unique(all_data_2[:,0:12], axis=0)

In [20]:
values_array[0]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  9], dtype=int64)

In [21]:
values_array = values_array[np.lexsort((-values_array[:,4], -values_array[:,5]))]

In [22]:
#swap index 0 and 1 of values_array
values_array[0][5]=0
values_array[1][5]=1
# so start of time is index 0, end of time index 1

In [23]:
values_array[0:1000]

array([[ -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,   1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  79,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  78,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  75,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  74,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  73,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  70,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  69,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  68,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  67,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  65,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  64,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  63,  

In [24]:
for i in range(len(values_array)):
    values_to_num[str(values_array[i])] = values_count
    num_to_values[values_count] = values_array[i]
    values_count += 1

In [25]:
print(len(values_array))
print(len(values_to_num))
print(len(num_to_values))

6329
6329
6329


In [26]:
#pickle the two dictionaries

with open('values_to_num.pickle', 'wb') as handle:
    pickle.dump(values_to_num, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('num_to_values.pickle', 'wb') as handle:
    pickle.dump(num_to_values, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [27]:
time_array = np.sort(np.unique(all_data_2[:,12], axis=0))

In [28]:
time_array

array([     0,      1,      2,      3,      4,      5,      6,      7,      8,      9,     10,     11,     12,     13,     14,     15,     16,     17,     18,     19,     20,     21,     22,     23,     24,     25,     26,     27,     28,     29,     30,     31,     32,     33,     34,     35,     36,     37,     38,     39,     40,     41,     42,     43,     44,     45,     46,     47,     48,     49,     50,     51,     52,     53,     54,     55,     56,     57,     58,     59,     60,     61,     62,     63,     64,     65,     66,     67,     68,     69,     70,     71,     72,     73,     74,     75,     76,     77,     78,     79,     80,     81,     82,     83,     84,     85,     86,     87,     88,     89,     90,     91,     92,     93,     94,     95,     96,     97,     98,     99,    100,    101,    102,    103,    104,    105,    106,    107,    108,    109,    110,    111,    112,    113,    114,    115,    116,    117,    118,    119,    120,    121,    122,    123,  

In [29]:
for i in range(len(time_array)):
    time_to_num[str(time_array[i])] = time_count
    num_to_times[time_count] = time_array[i]
    time_count += 1

In [30]:
print(len(time_array))
print(len(time_to_num))
print(len(num_to_times))

3904
3904
3904


In [31]:
#pickle the two dictionaries

with open('time_to_num.pickle', 'wb') as handle:
    pickle.dump(time_to_num, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('num_to_times.pickle', 'wb') as handle:
    pickle.dump(num_to_times, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [32]:
instruments_array = np.unique(all_data_2[:,13:], axis=0)

In [33]:
instruments_array

array([[-1, -1],
       [ 1,  0],
       [ 1,  2],
       [ 1,  6],
       [ 1,  7],
       [ 1, 16],
       [ 1, 18],
       [ 1, 19],
       [ 1, 20],
       [ 1, 24],
       [ 1, 34],
       [ 1, 40],
       [ 1, 41],
       [ 1, 42],
       [ 1, 43],
       [ 1, 45],
       [ 1, 47],
       [ 1, 48],
       [ 1, 49],
       [ 1, 51],
       [ 1, 52],
       [ 1, 53],
       [ 1, 56],
       [ 1, 57],
       [ 1, 58],
       [ 1, 59],
       [ 1, 60],
       [ 1, 63],
       [ 1, 64],
       [ 1, 65],
       [ 1, 67],
       [ 1, 68],
       [ 1, 69],
       [ 1, 70],
       [ 1, 71],
       [ 1, 73],
       [ 1, 74],
       [ 1, 75],
       [ 1, 78],
       [ 1, 79],
       [ 2,  0],
       [ 2,  2],
       [ 2,  6],
       [ 2,  7],
       [ 2, 19],
       [ 2, 20],
       [ 2, 24],
       [ 2, 40],
       [ 2, 41],
       [ 2, 42],
       [ 2, 43],
       [ 2, 45],
       [ 2, 47],
       [ 2, 48],
       [ 2, 49],
       [ 2, 51],
       [ 2, 52],
       [ 2, 53],
       [ 2, 56

In [34]:
for i in range(len(instruments_array)):
    instruments_to_num[str(instruments_array[i])] = instruments_count
    num_to_instruments[instruments_count] = instruments_array[i]
    instruments_count += 1

In [35]:
print(len(instruments_array))
print(len(instruments_to_num))
print(len(num_to_instruments))

143
143
143


In [36]:
#pickle the two dictionaries

with open('instruments_to_num.pickle', 'wb') as handle:
    pickle.dump(instruments_to_num, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('num_to_instruments.pickle', 'wb') as handle:
    pickle.dump(num_to_instruments, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [37]:
'''[note_on_note, note_on_velocity,
        control_change_control, control_change_value, program_change_program,
        end_marking, set_tempo_tempo,
        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,
        key_sig(turn into numbers), [time], instrument_num, orig_instrument_type]'''

'[note_on_note, note_on_velocity,\n        control_change_control, control_change_value, program_change_program,\n        end_marking, set_tempo_tempo,\n        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,\n        key_sig(turn into numbers), [time], instrument_num, orig_instrument_type]'