In [21]:
import numpy as np
import pickle
np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=np.inf)
from tokenizer import Tokenizer

In [52]:
tokenizer = Tokenizer()

In [53]:
all_data = np.load('all_unique_data.npy', allow_pickle=True)

In [54]:
tokenizer.fit(all_data)

values starting


100%|██████████| 5963/5963 [00:00<00:00, 23246.03it/s]


values done
time starting


100%|██████████| 524/524 [00:00<?, ?it/s]


time done
instruments starting


100%|██████████| 189/189 [00:00<00:00, 22708.93it/s]

instruments done


In [55]:
tokenizer.save_tokenizer()

tokenizer saved at tokenizer.pickle


In [56]:
tokenizer.load_tokenizer()

In [57]:
with open('all_data.pickle', 'rb') as handle:
    MIDI_list = pickle.load(handle)

In [58]:
len(MIDI_list)

419

In [59]:
MIDI_list[0][0:100]

array([[  0,   0,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1],
       [  1,   0,  -1,  -1,  -1,  -1,  -1,   0,   0,   1,   0],
       [  1,  16,  -1,  -1,  -1,  -1,  -1,   0,  16,   1,  16],
       [  1,  19,  -1,  -1,  -1,  -1,  -1,   0,  19,   1,  19],
       [  1,  19,  -1,  -1,  -1,  -1,  -1,   0,  19,   2,  19],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   1,  56],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   2,  56],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   3,  56],
       [  1,  57,  -1,  -1,  -1,  -1,  -1,   0,  57,   1,  57],
       [  1,  57,  -1,  -1,  -1,  -1,  -1,   0,  57,   2,  57],
       [  1,  58,  -1,  -1,  -1,  -1,  -1,   0,  58,   1,  58],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  56,   3,  56],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  57,   1,  57],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  57,   2,  57],
       [  1,  73,  -1,  -1,  -1,  -1,  -1,   0,  73,   1,  73],
       [  1,  73,  -1,  -1,  -1,  -1,  -

In [60]:
str(tokenizer.num_to_values[0])

'[ 0  0 -1 -1 -1 -1 -1]'

In [61]:
print(tokenizer.tokenize(MIDI_list[0][0:100]))

100%|██████████| 100/100 [00:00<00:00, 7928.44it/s]

[[  0   0   0]
 [  2   0   1]
 [  5   0  34]
 [  6   0  36]
 [  6   0  37]
 [ 27   0 141]
 [ 27   0 142]
 [ 27   0 143]
 [ 28   0 147]
 [ 28   0 148]
 [ 29   0 149]
 [ 30   0 143]
 [ 30   0 147]
 [ 30   0 148]
 [ 41   0 178]
 [ 41   0 179]
 [ 46   0  34]
 [ 46   0  36]
 [ 46   0 141]
 [ 46   0 142]
 [ 46   0 143]
 [ 46   0 147]
 [ 46   0 148]
 [ 46   0 149]
 [ 46   0 178]
 [ 46   0 179]
 [ 47   0 178]
 [ 51   0 179]
 [ 54   0  36]
 [ 61   0 147]
 [ 63   0 142]
 [ 66   0 143]
 [ 72   0 143]
 [ 72   0 147]
 [ 72   0 148]
 [ 73   0  34]
 [ 85   0 141]
 [ 87   0 148]
 [ 91   0 149]
 [ 92   0  34]
 [ 92   0  36]
 [ 92   0 141]
 [ 92   0 142]
 [ 92   0 143]
 [ 92   0 147]
 [ 92   0 148]
 [ 92   0 149]
 [ 92   0 178]
 [ 92   0 179]
 [ 93   0  34]
 [ 93   0  36]
 [ 93   0 141]
 [ 93   0 142]
 [ 93   0 143]
 [ 93   0 147]
 [ 93   0 148]
 [ 93   0 149]
 [ 93   0 151]
 [ 93   0 154]
 [ 93   0 156]
 [ 93   0 178]
 [ 93   0 179]
 [ 94   0  34]
 [ 94   0  36]
 [ 94   0 141]
 [ 94   0 142]
 [ 94   0 

In [62]:
tokenized_list = tokenizer.tokenize_all(MIDI_list)

100%|██████████| 1239/1239 [00:00<00:00, 13786.29it/s]

100%|██████████| 672/672 [00:00<00:00, 10411.39it/s]

100%|██████████| 900/900 [00:00<00:00, 13972.37it/s]

100%|██████████| 994/994 [00:00<00:00, 12765.27it/s]

100%|██████████| 1304/1304 [00:00<00:00, 13557.04it/s]

100%|██████████| 1336/1336 [00:00<00:00, 14432.68it/s]

100%|██████████| 977/977 [00:00<00:00, 13551.62it/s]

100%|██████████| 555/555 [00:00<00:00, 11563.28it/s]

100%|██████████| 315/315 [00:00<00:00, 13057.33it/s]

100%|██████████| 313/313 [00:00<00:00, 9788.52it/s]

100%|██████████| 242/242 [00:00<00:00, 10080.96it/s]

100%|██████████| 490/490 [00:00<00:00, 12245.71it/s]

100%|██████████| 412/412 [00:00<00:00, 12454.08it/s]

100%|██████████| 1146/1146 [00:00<00:00, 13462.60it/s]

100%|██████████| 872/872 [00:00<00:00, 11952.24it/s]

100%|██████████| 846/846 [00:00<00:00, 13048.59it/s]

100%|██████████| 616/616 [00:00<00:00, 11190.43it/s]

100%|██████████| 460/460 [00:00<00:00, 6960.27it/s]

100%|██████████| 419/4

In [63]:
tokenized_list[0][0:100]

array([[  0,   0,   0],
       [  2,   0,   1],
       [  5,   0,  34],
       [  6,   0,  36],
       [  6,   0,  37],
       [ 27,   0, 141],
       [ 27,   0, 142],
       [ 27,   0, 143],
       [ 28,   0, 147],
       [ 28,   0, 148],
       [ 29,   0, 149],
       [ 30,   0, 143],
       [ 30,   0, 147],
       [ 30,   0, 148],
       [ 41,   0, 178],
       [ 41,   0, 179],
       [ 46,   0,  34],
       [ 46,   0,  36],
       [ 46,   0, 141],
       [ 46,   0, 142],
       [ 46,   0, 143],
       [ 46,   0, 147],
       [ 46,   0, 148],
       [ 46,   0, 149],
       [ 46,   0, 178],
       [ 46,   0, 179],
       [ 47,   0, 178],
       [ 51,   0, 179],
       [ 54,   0,  36],
       [ 61,   0, 147],
       [ 63,   0, 142],
       [ 66,   0, 143],
       [ 72,   0, 143],
       [ 72,   0, 147],
       [ 72,   0, 148],
       [ 73,   0,  34],
       [ 85,   0, 141],
       [ 87,   0, 148],
       [ 91,   0, 149],
       [ 92,   0,  34],
       [ 92,   0,  36],
       [ 92,   0

In [67]:
tokenized_list[0][-100:]

array([[5110,    0,  156],
       [5495,    0,  179],
       [5636,    0,  178],
       [4536,  230,   34],
       [4536,    0,  142],
       [5479,    0,   36],
       [5479,    0,  156],
       [5674,    0,  179],
       [5812,    0,  178],
       [ 299,  119,  149],
       [ 364,    0,  141],
       [ 716,    0,  154],
       [1641,    0,  151],
       [2302,    0,    1],
       [2302,    0,  142],
       [2796,    0,    1],
       [2796,    0,  142],
       [3521,    0,   37],
       [3521,    0,  156],
       [3846,    0,   34],
       [3846,    0,  142],
       [4045,    0,   37],
       [4045,    0,  156],
       [4246,    0,  179],
       [4448,    0,   34],
       [4448,    0,  142],
       [4758,    0,  178],
       [4758,    0,  179],
       [5055,    0,   36],
       [5055,    0,  156],
       [5219,    0,  178],
       [5438,    0,   36],
       [5438,    0,  156],
       [5490,    0,  179],
       [5627,    0,  178],
       [5637,    0,  179],
       [5781,    0,  178],
 

In [68]:
np.array_equal(tokenizer.detokenize(tokenized_list[0][0:100]), MIDI_list[0][0:100])

100%|██████████| 100/100 [00:00<00:00, 83651.85it/s]


True

array([[  0,   0,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1],
       [  1,   0,  -1,  -1,  -1,  -1,  -1,   0,   0,   1,   0],
       [  1,  16,  -1,  -1,  -1,  -1,  -1,   0,  16,   1,  16],
       [  1,  19,  -1,  -1,  -1,  -1,  -1,   0,  19,   1,  19],
       [  1,  19,  -1,  -1,  -1,  -1,  -1,   0,  19,   2,  19],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   1,  56],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   2,  56],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   3,  56],
       [  1,  57,  -1,  -1,  -1,  -1,  -1,   0,  57,   1,  57],
       [  1,  57,  -1,  -1,  -1,  -1,  -1,   0,  57,   2,  57],
       [  1,  58,  -1,  -1,  -1,  -1,  -1,   0,  58,   1,  58],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  56,   3,  56],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  57,   1,  57],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  57,   2,  57],
       [  1,  73,  -1,  -1,  -1,  -1,  -1,   0,  73,   1,  73],
       [  1,  73,  -1,  -1,  -1,  -1,  -

In [69]:
with open('tokenized_list.pickle', 'wb') as handle:
    pickle.dump(tokenized_list, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
# below was the old approach

In [2]:
all_data_o = np.load('all_unique_data.npy', allow_pickle=True)

In [5]:
all_data_o[0:10]

array([[ 0.,  0., -1., -1., -1., -1., -1.,  0., -1., -1.],
       [ 0.,  1., -1., -1., -1., -1., -1.,  0., -1., -1.],
       [ 1.,  0., -1., -1., -1., -1., -1.,  0.,  1.,  0.],
       [ 1.,  0., -1., -1., -1., -1., -1.,  0.,  2.,  0.],
       [ 1.,  0., -1., -1., -1., -1., -1.,  0.,  3.,  0.],
       [ 1.,  0., -1., -1., -1., -1., -1.,  0.,  4.,  0.],
       [ 1.,  6., -1., -1., -1., -1., -1.,  0.,  1.,  6.],
       [ 1.,  6., -1., -1., -1., -1., -1.,  0.,  2.,  6.],
       [ 1.,  6., -1., -1., -1., -1., -1.,  0.,  3.,  6.],
       [ 1.,  6., -1., -1., -1., -1., -1.,  0.,  4.,  6.]])

In [6]:
all_data = all_data_o.reshape((-1, 10))
#change dtype of all_data to int64

all_data_2 = all_data.astype(np.int64)

In [7]:
all_data_2[0:10000]

array([[     0,      0,     -1,     -1,     -1,     -1,     -1,      0,     -1,     -1],
       [     0,      1,     -1,     -1,     -1,     -1,     -1,      0,     -1,     -1],
       [     1,      0,     -1,     -1,     -1,     -1,     -1,      0,      1,      0],
       [     1,      0,     -1,     -1,     -1,     -1,     -1,      0,      2,      0],
       [     1,      0,     -1,     -1,     -1,     -1,     -1,      0,      3,      0],
       [     1,      0,     -1,     -1,     -1,     -1,     -1,      0,      4,      0],
       [     1,      6,     -1,     -1,     -1,     -1,     -1,      0,      1,      6],
       [     1,      6,     -1,     -1,     -1,     -1,     -1,      0,      2,      6],
       [     1,      6,     -1,     -1,     -1,     -1,     -1,      0,      3,      6],
       [     1,      6,     -1,     -1,     -1,     -1,     -1,      0,      4,      6],
       [     1,      6,     -1,     -1,     -1,     -1,     -1,      0,      5,      6],
       [     1,      

In [16]:
# pickle values up to index 11 (values), pickle index 12 (time), pickle values from index 14 to end (instruments)

In [8]:
num_to_values = {}
values_to_num = {}

time_to_num = {}
num_to_times = {}

num_to_instruments = {}
instruments_to_num = {}

In [9]:
values_count = 0
time_count = 0
instruments_count = 0

In [10]:
values_array = np.unique(all_data_2[:,0:6], axis=0)

In [28]:
values_array[0:1000]

array([[  0,   0,  -1,  -1,  -1,  -1],
       [  0,   1,  -1,  -1,  -1,  -1],
       [  1,   0,  -1,  -1,  -1,  -1],
       [  1,   6,  -1,  -1,  -1,  -1],
       [  1,   7,  -1,  -1,  -1,  -1],
       [  1,  16,  -1,  -1,  -1,  -1],
       [  1,  19,  -1,  -1,  -1,  -1],
       [  1,  20,  -1,  -1,  -1,  -1],
       [  1,  24,  -1,  -1,  -1,  -1],
       [  1,  25,  -1,  -1,  -1,  -1],
       [  1,  26,  -1,  -1,  -1,  -1],
       [  1,  28,  -1,  -1,  -1,  -1],
       [  1,  32,  -1,  -1,  -1,  -1],
       [  1,  34,  -1,  -1,  -1,  -1],
       [  1,  36,  -1,  -1,  -1,  -1],
       [  1,  37,  -1,  -1,  -1,  -1],
       [  1,  40,  -1,  -1,  -1,  -1],
       [  1,  41,  -1,  -1,  -1,  -1],
       [  1,  42,  -1,  -1,  -1,  -1],
       [  1,  43,  -1,  -1,  -1,  -1],
       [  1,  44,  -1,  -1,  -1,  -1],
       [  1,  45,  -1,  -1,  -1,  -1],
       [  1,  47,  -1,  -1,  -1,  -1],
       [  1,  48,  -1,  -1,  -1,  -1],
       [  1,  50,  -1,  -1,  -1,  -1],
       [  1,  51,  -1,  -

In [29]:
for i in range(len(values_array)):
    values_to_num[str(values_array[i])] = values_count
    num_to_values[values_count] = values_array[i]
    values_count += 1

In [30]:
print(len(values_array))
print(len(values_to_num))
print(len(num_to_values))

5963
5963
5963


In [31]:
#pickle the two dictionaries
with open('values_to_num.pickle', 'wb') as handle:
    pickle.dump(values_to_num, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('num_to_values.pickle', 'wb') as handle:
    pickle.dump(num_to_values, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [32]:
time_array = np.sort(np.unique(all_data_2[:,7], axis=0))

In [33]:
time_array

array([      0,       1,       2,       3,       4,       5,       6,       7,       8,       9,      10,      11,      12,      13,      14,      15,      16,      17,      18,      19,      20,      21,      22,      23,      24,      25,      26,      27,      28,      29,      30,      31,      32,      33,      34,      35,      36,      37,      38,      39,      40,      41,      42,      43,      44,      45,      46,      47,      48,      49,      50,      51,      52,      53,      54,      55,      56,      57,      58,      59,      60,      61,      62,      63,      64,      65,      66,      67,      68,      69,      70,      71,      72,      73,      74,      75,      76,      77,      78,      79,      80,      81,      82,      83,      84,      85,      86,      87,      88,      89,      90,      91,      92,      93,      94,      95,      96,      97,      98,      99,     100,     101,     102,     103,     104,     105,     106,     107,     108,     109,    

In [34]:
for i in range(len(time_array)):
    time_to_num[str(time_array[i])] = time_count
    num_to_times[time_count] = time_array[i]
    time_count += 1

In [35]:
print(len(time_array))
print(len(time_to_num))
print(len(num_to_times))

3402
3402
3402


In [36]:
#pickle the two dictionaries

with open('time_to_num.pickle', 'wb') as handle:
    pickle.dump(time_to_num, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('num_to_times.pickle', 'wb') as handle:
    pickle.dump(num_to_times, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [42]:
instruments_array = np.unique(all_data_2[:,8:], axis=0)

In [43]:
instruments_array

array([[-1, -1],
       [ 1,  0],
       [ 1,  6],
       [ 1,  7],
       [ 1, 16],
       [ 1, 19],
       [ 1, 20],
       [ 1, 24],
       [ 1, 25],
       [ 1, 34],
       [ 1, 40],
       [ 1, 41],
       [ 1, 42],
       [ 1, 43],
       [ 1, 47],
       [ 1, 48],
       [ 1, 50],
       [ 1, 52],
       [ 1, 56],
       [ 1, 57],
       [ 1, 58],
       [ 1, 60],
       [ 1, 62],
       [ 1, 64],
       [ 1, 65],
       [ 1, 67],
       [ 1, 68],
       [ 1, 69],
       [ 1, 70],
       [ 1, 71],
       [ 1, 73],
       [ 1, 74],
       [ 1, 75],
       [ 1, 78],
       [ 1, 79],
       [ 2,  0],
       [ 2,  6],
       [ 2,  7],
       [ 2, 16],
       [ 2, 19],
       [ 2, 20],
       [ 2, 24],
       [ 2, 40],
       [ 2, 41],
       [ 2, 42],
       [ 2, 43],
       [ 2, 47],
       [ 2, 48],
       [ 2, 50],
       [ 2, 52],
       [ 2, 56],
       [ 2, 57],
       [ 2, 60],
       [ 2, 68],
       [ 2, 69],
       [ 2, 70],
       [ 2, 73],
       [ 2, 74],
       [ 2, 78

In [44]:
for i in range(len(instruments_array)):
    instruments_to_num[str(instruments_array[i])] = instruments_count
    num_to_instruments[instruments_count] = instruments_array[i]
    instruments_count += 1

In [45]:
print(len(instruments_array))
print(len(instruments_to_num))
print(len(num_to_instruments))

127
127
127


In [46]:
#pickle the two dictionaries

with open('instruments_to_num.pickle', 'wb') as handle:
    pickle.dump(instruments_to_num, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('num_to_instruments.pickle', 'wb') as handle:
    pickle.dump(num_to_instruments, handle, protocol=pickle.HIGHEST_PROTOCOL)