In [1]:
import numpy as np
import pickle
np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=np.inf)
from tokenizer import Tokenizer

In [2]:
#tokenizer = Tokenizer()

In [3]:
#all_data = np.load('all_unique_data.npy', allow_pickle=True)

In [4]:
#tokenizer.fit(all_data)

In [5]:
#tokenizer.clean(15)

In [6]:
#tokenizer.save_tokenizer()

In [7]:
#tokenizer.load_tokenizer()

In [8]:
with open('all_data.pickle', 'rb') as handle:
    MIDI_list = pickle.load(handle)

In [9]:
tokenizer = Tokenizer()
cleaned_data = tokenizer.fit_tokenize_clean(MIDI_list, 5)

values starting


100%|██████████| 5964/5964 [00:00<00:00, 21928.92it/s]


values done
time starting


100%|██████████| 524/524 [00:00<00:00, 524538.26it/s]


time done
instruments starting


100%|██████████| 189/189 [00:00<00:00, 37755.93it/s]


instruments done


100%|██████████| 819/819 [00:00<00:00, 9723.63it/s]

100%|██████████| 663/663 [00:00<00:00, 9337.36it/s]

100%|██████████| 358/358 [00:00<00:00, 13219.36it/s]

100%|██████████| 672/672 [00:00<00:00, 9359.74it/s]

100%|██████████| 994/994 [00:00<00:00, 14235.80it/s]

100%|██████████| 555/555 [00:00<00:00, 11966.85it/s]

100%|██████████| 315/315 [00:00<00:00, 10101.27it/s]

100%|██████████| 313/313 [00:00<00:00, 8283.54it/s]

100%|██████████| 479/479 [00:00<00:00, 8785.28it/s]

100%|██████████| 1462/1462 [00:00<00:00, 11160.42it/s]

100%|██████████| 13006/13006 [00:01<00:00, 10091.44it/s][A

100%|██████████| 858/858 [00:00<00:00, 10048.14it/s]

100%|██████████| 649/649 [00:00<00:00, 9185.00it/s]

100%|██████████| 851/851 [00:00<00:00, 9459.67it/s]

100%|██████████| 894/894 [00:00<00:00, 11495.12it/s]

100%|██████████| 832/832 [00:00<00:00, 11969.18it/s]

100%|██████████| 460/460 [00:00<00:00, 6948.14it/s]

100%|██████████| 901/901 [00:00<00:00, 11414.50it/s]

100%|██████████| 824/824 [00

In [10]:
print(len(tokenizer.num_to_values))
print(len(tokenizer.num_to_times))
print(len(tokenizer.num_to_instruments))

4347
298
189


In [11]:
tokenizer.save_tokenizer()

tokenizer saved at tokenizer.pickle


In [12]:
tokenizer.load_tokenizer()

In [13]:
len(MIDI_list)

464

In [14]:
MIDI_list[0][0:100]

array([[  0,   0,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1],
       [  1,   0,  -1,  -1,  -1,  -1,  -1,   0,   0,   1,   0],
       [  1,  16,  -1,  -1,  -1,  -1,  -1,   0,  16,   1,  16],
       [  1,  19,  -1,  -1,  -1,  -1,  -1,   0,  19,   1,  19],
       [  1,  19,  -1,  -1,  -1,  -1,  -1,   0,  19,   2,  19],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   1,  56],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   2,  56],
       [  1,  56,  -1,  -1,  -1,  -1,  -1,   0,  56,   3,  56],
       [  1,  57,  -1,  -1,  -1,  -1,  -1,   0,  57,   1,  57],
       [  1,  57,  -1,  -1,  -1,  -1,  -1,   0,  57,   2,  57],
       [  1,  58,  -1,  -1,  -1,  -1,  -1,   0,  58,   1,  58],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  56,   3,  56],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  57,   1,  57],
       [  1,  59,  -1,  -1,  -1,  -1,  -1,   0,  57,   2,  57],
       [  1,  73,  -1,  -1,  -1,  -1,  -1,   0,  73,   1,  73],
       [  1,  73,  -1,  -1,  -1,  -1,  -

In [15]:
str(tokenizer.num_to_values[0])

'[ 0  0 -1 -1 -1 -1 -1]'

In [16]:
print(tokenizer.tokenize(MIDI_list[0][0:100]))

100%|██████████| 100/100 [00:00<00:00, 6104.00it/s]

[[  0   0   0]
 [  2   0   1]
 [  5   0  34]
 [  6   0  36]
 [  6   0  37]
 [ 19   0 141]
 [ 19   0 142]
 [ 19   0 143]
 [ 20   0 147]
 [ 20   0 148]
 [ 21   0 149]
 [ 22   0 143]
 [ 22   0 147]
 [ 22   0 148]
 [ 30   0 178]
 [ 30   0 179]
 [ 35   0  34]
 [ 35   0  36]
 [ 35   0 141]
 [ 35   0 142]
 [ 35   0 149]
 [ 35   0 151]
 [ 35   0 154]
 [ 35   0 156]
 [ 35   0 178]
 [ 35   0 179]
 [  0   0   0]
 [  0   0   0]
 [ 36   0  36]
 [ 37   0 151]
 [ 38   0 142]
 [ 40   0 156]
 [ 43   0 151]
 [ 43   0 154]
 [ 43   0 156]
 [ 44   0  34]
 [  0   0   0]
 [ 49   0 154]
 [ 50   0 149]
 [ 51   0  34]
 [ 51   0  36]
 [ 51   0 141]
 [ 51   0 142]
 [ 51   0 149]
 [ 51   0 151]
 [ 51   0 154]
 [ 51   0 156]
 [ 51   0 178]
 [ 51   0 179]
 [ 52   0  34]
 [ 52   0  36]
 [ 52   0 141]
 [ 52   0 142]
 [ 52   0 149]
 [ 52   0 151]
 [ 52   0 154]
 [ 52   0 156]
 [ 52   0 178]
 [ 52   0 179]
 [ 53   0  34]
 [ 53   0  36]
 [ 53   0 141]
 [ 53   0 142]
 [ 53   0 149]
 [ 53   0 151]
 [ 53   0 154]
 [ 53   0 

In [17]:
cleaned_data[0][0:100]

array([[  0,   0,   0],
       [  2,   0,   1],
       [  5,   0,  34],
       [  6,   0,  36],
       [  6,   0,  37],
       [ 19,   0, 141],
       [ 19,   0, 142],
       [ 19,   0, 143],
       [ 20,   0, 147],
       [ 20,   0, 148],
       [ 21,   0, 149],
       [ 22,   0, 143],
       [ 22,   0, 147],
       [ 22,   0, 148],
       [ 30,   0, 178],
       [ 30,   0, 179],
       [ 35,   0,  34],
       [ 35,   0,  36],
       [ 35,   0, 141],
       [ 35,   0, 142],
       [ 35,   0, 149],
       [ 35,   0, 151],
       [ 35,   0, 154],
       [ 35,   0, 156],
       [ 35,   0, 178],
       [ 35,   0, 179],
       [  0,   0,   0],
       [  0,   0,   0],
       [ 36,   0,  36],
       [ 37,   0, 151],
       [ 38,   0, 142],
       [ 40,   0, 156],
       [ 43,   0, 151],
       [ 43,   0, 154],
       [ 43,   0, 156],
       [ 44,   0,  34],
       [  0,   0,   0],
       [ 49,   0, 154],
       [ 50,   0, 149],
       [ 51,   0,  34],
       [ 51,   0,  36],
       [ 51,   0

In [18]:
cleaned_data[0][-100:]

array([[3963,    0,  156],
       [4191,    0,  179],
       [4244,    0,  178],
       [3529,  197,   34],
       [3529,    0,  142],
       [4181,    0,   36],
       [4181,    0,  156],
       [4259,    0,  179],
       [4299,    0,  178],
       [ 234,  117,  149],
       [ 253,    0,  141],
       [ 412,    0,  154],
       [1090,    0,  151],
       [1644,    0,    1],
       [1644,    0,  142],
       [2061,    0,    1],
       [2061,    0,  142],
       [2659,    0,   37],
       [2659,    0,  156],
       [2951,    0,   34],
       [2951,    0,  142],
       [3123,    0,   37],
       [3123,    0,  156],
       [3292,    0,  179],
       [3453,    0,   34],
       [3453,    0,  142],
       [3706,    0,  178],
       [3706,    0,  179],
       [3932,    0,   36],
       [3932,    0,  156],
       [4043,    0,  178],
       [4163,    0,   36],
       [4163,    0,  156],
       [4186,    0,  179],
       [4241,    0,  178],
       [4245,    0,  179],
       [4289,    0,  178],
 

In [19]:
np.array_equal(tokenizer.detokenize(cleaned_data[0][0:100]), MIDI_list[0][0:100])

100%|██████████| 100/100 [00:00<00:00, 49973.84it/s]


False

In [20]:
with open('tokenized_list.pickle', 'wb') as handle:
    pickle.dump(cleaned_data, handle, protocol=pickle.HIGHEST_PROTOCOL)