In [1]:
import pickle
import numpy as np

In [2]:
all_data = []
with (open("all_data.pickle", "rb")) as openfile:
    try:
        all_data = (pickle.load(openfile))
    except EOFError:
        pass

In [3]:
#get largest value within all_data
largest_values = []
for i in all_data:
    largest_values.append(np.max(i))
print(np.max(largest_values))

2998560


In [4]:
largest_length = 0
for i in all_data:
    if len(i) > largest_length:
        largest_length = len(i)
print(largest_length)

102188


In [3]:
full_data = np.array([])
for i in range(len(all_data)):
    full_data = np.append(full_data, all_data[i])

In [4]:
full_data = full_data.reshape((-1,16))

In [5]:
len(full_data)

2384400

In [6]:
un_full_data = np.unique(full_data, axis = 0)

In [7]:
len(un_full_data)

377730

In [8]:
'''[note_on_note, note_on_velocity,
        control_change_control, control_change_value, program_change_program,
        end_marking, set_tempo_tempo,
        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,
        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'''

'[note_on_note, note_on_velocity,\n        control_change_control, control_change_value, program_change_program,\n        end_marking, set_tempo_tempo,\n        time_sig_num, itme_sig_den, time_sig_clocksperclick, time_sig_notated_32nd,\n        key_sig(turn into numbers), [time], instrument_type, instrument_num, orig_instrument_type]'

In [14]:
data_wo_time = un_full_data[:,[0,1,2,3,4,5,6,7,8,9,10,11,13,14,15]]

In [15]:
data_wo_time = np.unique(data_wo_time, axis = 0)

In [16]:
len(data_wo_time)

62781

In [17]:
data_instrs = un_full_data[:,[13,14,15]]

In [18]:
data_instrs = np.unique(data_instrs, axis = 0)

In [19]:
len(data_instrs)

229

In [20]:
data_wo_instruments_or_time = un_full_data[:,[0,1,2,3,4,5,6,7,8,9,10,11]]

In [21]:
data_wo_instruments_or_time = np.unique(data_wo_instruments_or_time, axis = 0)

In [22]:
len(data_wo_instruments_or_time)

6328

In [23]:
data_time_sig_clocks_32nd = un_full_data[:,[9,10]]

In [24]:
data_time_sig_clocks_32nd = np.unique(data_time_sig_clocks_32nd, axis = 0)

In [25]:
len(data_time_sig_clocks_32nd)

9

In [26]:
data_time_sig_clocks_32nd

array([[-1., -1.],
       [ 6.,  8.],
       [12.,  8.],
       [18.,  8.],
       [24.,  8.],
       [36.,  8.],
       [48.,  8.],
       [72.,  8.],
       [96.,  8.]])

In [27]:
data_time_sig_num_den = un_full_data[:,[7,8]]

In [28]:
data_time_sig_num_den = np.unique(data_time_sig_num_den, axis = 0)

In [29]:
len(data_time_sig_num_den)

25

In [30]:
data_time_sig_num_den

array([[-1., -1.],
       [ 1.,  2.],
       [ 1.,  4.],
       [ 1.,  8.],
       [ 1., 16.],
       [ 2.,  2.],
       [ 2.,  4.],
       [ 2.,  8.],
       [ 3.,  2.],
       [ 3.,  4.],
       [ 3.,  8.],
       [ 4.,  2.],
       [ 4.,  4.],
       [ 5.,  8.],
       [ 6.,  4.],
       [ 6.,  8.],
       [ 8.,  4.],
       [ 8.,  8.],
       [ 9.,  4.],
       [ 9.,  8.],
       [ 9., 16.],
       [11.,  8.],
       [12.,  8.],
       [12., 16.],
       [15., 16.]])

In [35]:
times = un_full_data[:,[12]]

In [36]:
times = np.unique(times, axis = 0)

In [37]:
len(times)

11852

In [38]:
times

array([[-391168.],
       [-285420.],
       [-263168.],
       ...,
       [2810160.],
       [2810400.],
       [2998560.]])

In [ ]:
#wtf??????????